FROM nielcho/base:v1
MAINTAINER nielcho "danielnanuk@gmail.com"
ENV REFRESHED_AT 2016-08-30

ADD jdk-8u101-linux-x64.tar.gz /opt/ 
ENV JAVA_HOME /opt/jdk1.8.0_101
ENV PATH $PATH:/opt/jdk1.8.0_101/bin
